// <auto-generated />
using System;
using CarRental.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarRental.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    partial class CarRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("GenerationId")
                        .HasColumnType("integer");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("LicensePlate");

                    b.ToTable("cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            GenerationId = 1,
                            LicensePlate = "A123BC777"
                        },
                        new
                        {
                            Id = 2,
                            Color = "White",
                            GenerationId = 1,
                            LicensePlate = "B456OP777"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Silver",
                            GenerationId = 2,
                            LicensePlate = "E789TT777"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Blue",
                            GenerationId = 3,
                            LicensePlate = "K321MM777"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black",
                            GenerationId = 3,
                            LicensePlate = "M654HH777"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Red",
                            GenerationId = 4,
                            LicensePlate = "O987PP777"
                        },
                        new
                        {
                            Id = 7,
                            Color = "White",
                            GenerationId = 4,
                            LicensePlate = "P159CC777"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Gray",
                            GenerationId = 5,
                            LicensePlate = "C753YY777"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Black",
                            GenerationId = 6,
                            LicensePlate = "T456FF777"
                        },
                        new
                        {
                            Id = 10,
                            Color = "White",
                            GenerationId = 6,
                            LicensePlate = "Y789XX777"
                        },
                        new
                        {
                            Id = 11,
                            Color = "Blue",
                            GenerationId = 7,
                            LicensePlate = "X123KK777"
                        },
                        new
                        {
                            Id = 12,
                            Color = "Green",
                            GenerationId = 8,
                            LicensePlate = "C456LL777"
                        },
                        new
                        {
                            Id = 13,
                            Color = "Silver",
                            GenerationId = 9,
                            LicensePlate = "Z789MM777"
                        },
                        new
                        {
                            Id = 14,
                            Color = "Red",
                            GenerationId = 10,
                            LicensePlate = "H321HH777"
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodyType")
                        .HasColumnType("integer");

                    b.Property<int?>("Class")
                        .HasColumnType("integer");

                    b.Property<int?>("DriveType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SeatsNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("car_models", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyType = 2,
                            Class = 3,
                            DriveType = 0,
                            Name = "Toyota Camry",
                            SeatsNumber = 5
                        },
                        new
                        {
                            Id = 2,
                            BodyType = 3,
                            Class = 4,
                            DriveType = 2,
                            Name = "BMW X5",
                            SeatsNumber = 5
                        },
                        new
                        {
                            Id = 3,
                            BodyType = 2,
                            Class = 1,
                            DriveType = 0,
                            Name = "Lada Vesta",
                            SeatsNumber = 5
                        },
                        new
                        {
                            Id = 4,
                            BodyType = 0,
                            Class = 1,
                            DriveType = 0,
                            Name = "Kia Rio",
                            SeatsNumber = 5
                        },
                        new
                        {
                            Id = 5,
                            BodyType = 2,
                            Class = 5,
                            DriveType = 1,
                            Name = "Mercedes S-Class",
                            SeatsNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            BodyType = 0,
                            Class = 1,
                            DriveType = 0,
                            Name = "Volkswagen Polo",
                            SeatsNumber = 5
                        },
                        new
                        {
                            Id = 7,
                            BodyType = 4,
                            Class = 2,
                            DriveType = 0,
                            Name = "Hyundai Creta",
                            SeatsNumber = 5
                        },
                        new
                        {
                            Id = 8,
                            BodyType = 1,
                            Class = 2,
                            DriveType = 0,
                            Name = "Skoda Octavia",
                            SeatsNumber = 5
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("DriverLicense")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1985, 5, 15),
                            DriverLicense = "7712345678",
                            FirstName = "Ivan",
                            LastName = "Ivanov",
                            Patronymic = "Ivanovich"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1990, 8, 22),
                            DriverLicense = "7723456789",
                            FirstName = "Petr",
                            LastName = "Petrov",
                            Patronymic = "Petrovich"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1988, 3, 10),
                            DriverLicense = "7734567890",
                            FirstName = "Alexey",
                            LastName = "Sidorov",
                            Patronymic = "Sergeevich"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1992, 11, 5),
                            DriverLicense = "7745678901",
                            FirstName = "Dmitry",
                            LastName = "Smirnov",
                            Patronymic = "Andreevich"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1987, 7, 18),
                            DriverLicense = "7756789012",
                            FirstName = "Sergey",
                            LastName = "Kuznetsov",
                            Patronymic = "Mikhailovich"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1995, 2, 28),
                            DriverLicense = "7767890123",
                            FirstName = "Mikhail",
                            LastName = "Popov",
                            Patronymic = "Dmitrievich"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1983, 9, 12),
                            DriverLicense = "7778901234",
                            FirstName = "Andrey",
                            LastName = "Volkov",
                            Patronymic = "Alexeevich"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1991, 6, 8),
                            DriverLicense = "7789012345",
                            FirstName = "Pavel",
                            LastName = "Sokolov",
                            Patronymic = "Nikolaevich"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1989, 4, 25),
                            DriverLicense = "7790123456",
                            FirstName = "Nikolay",
                            LastName = "Novikov",
                            Patronymic = "Vladimirovich"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1993, 12, 3),
                            DriverLicense = "7701234567",
                            FirstName = "Vladimir",
                            LastName = "Morozov",
                            Patronymic = "Olegovich"
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.ModelGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("EngineVolume")
                        .HasColumnType("double precision");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int?>("TransmissionType")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("model_generations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngineVolume = 2.5,
                            ModelId = 1,
                            PricePerHour = 2000m,
                            TransmissionType = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            EngineVolume = 2.0,
                            ModelId = 1,
                            PricePerHour = 2200m,
                            TransmissionType = 0,
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            EngineVolume = 3.0,
                            ModelId = 2,
                            PricePerHour = 3500m,
                            TransmissionType = 0,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            EngineVolume = 1.6000000238418579,
                            ModelId = 3,
                            PricePerHour = 900m,
                            TransmissionType = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            EngineVolume = 1.6000000238418579,
                            ModelId = 4,
                            PricePerHour = 1100m,
                            TransmissionType = 2,
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            EngineVolume = 3.0,
                            ModelId = 5,
                            PricePerHour = 5000m,
                            TransmissionType = 0,
                            Year = 2022
                        },
                        new
                        {
                            Id = 7,
                            EngineVolume = 1.3999999761581421,
                            ModelId = 6,
                            PricePerHour = 950m,
                            TransmissionType = 1,
                            Year = 2021
                        },
                        new
                        {
                            Id = 8,
                            EngineVolume = 2.0,
                            ModelId = 7,
                            PricePerHour = 1800m,
                            TransmissionType = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 9,
                            EngineVolume = 1.7999999523162842,
                            ModelId = 8,
                            PricePerHour = 1700m,
                            TransmissionType = 0,
                            Year = 2022
                        },
                        new
                        {
                            Id = 10,
                            EngineVolume = 1.3999999761581421,
                            ModelId = 6,
                            PricePerHour = 1000m,
                            TransmissionType = 3,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.RentalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RentStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("rental_logs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ClientId = 1,
                            Duration = 24.0,
                            RentStartDate = new DateTime(2024, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CarId = 1,
                            ClientId = 2,
                            Duration = 48.0,
                            RentStartDate = new DateTime(2024, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CarId = 1,
                            ClientId = 3,
                            Duration = 12.0,
                            RentStartDate = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CarId = 2,
                            ClientId = 4,
                            Duration = 72.0,
                            RentStartDate = new DateTime(2024, 1, 20, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CarId = 2,
                            ClientId = 1,
                            Duration = 24.0,
                            RentStartDate = new DateTime(2024, 2, 5, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CarId = 3,
                            ClientId = 5,
                            Duration = 36.0,
                            RentStartDate = new DateTime(2024, 1, 25, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CarId = 4,
                            ClientId = 6,
                            Duration = 24.0,
                            RentStartDate = new DateTime(2024, 2, 10, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CarId = 4,
                            ClientId = 2,
                            Duration = 48.0,
                            RentStartDate = new DateTime(2024, 2, 12, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CarId = 5,
                            ClientId = 7,
                            Duration = 12.0,
                            RentStartDate = new DateTime(2024, 1, 30, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CarId = 6,
                            ClientId = 8,
                            Duration = 60.0,
                            RentStartDate = new DateTime(2024, 2, 3, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CarId = 7,
                            ClientId = 1,
                            Duration = 18.0,
                            RentStartDate = new DateTime(2024, 2, 7, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CarId = 8,
                            ClientId = 4,
                            Duration = 24.0,
                            RentStartDate = new DateTime(2024, 2, 9, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CarId = 9,
                            ClientId = 5,
                            Duration = 36.0,
                            RentStartDate = new DateTime(2024, 2, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CarId = 10,
                            ClientId = 6,
                            Duration = 48.0,
                            RentStartDate = new DateTime(2024, 2, 13, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CarId = 11,
                            ClientId = 7,
                            Duration = 24.0,
                            RentStartDate = new DateTime(2024, 2, 14, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CarId = 14,
                            ClientId = 8,
                            Duration = 12.0,
                            RentStartDate = new DateTime(2024, 2, 15, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CarId = 12,
                            ClientId = 9,
                            Duration = 48.0,
                            RentStartDate = new DateTime(2024, 2, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CarId = 13,
                            ClientId = 10,
                            Duration = 24.0,
                            RentStartDate = new DateTime(2024, 2, 17, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CarId = 1,
                            ClientId = 3,
                            Duration = 36.0,
                            RentStartDate = new DateTime(2024, 2, 18, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CarId = 2,
                            ClientId = 5,
                            Duration = 24.0,
                            RentStartDate = new DateTime(2024, 2, 19, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CarId = 4,
                            ClientId = 7,
                            Duration = 18.0,
                            RentStartDate = new DateTime(2024, 2, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CarId = 6,
                            ClientId = 9,
                            Duration = 72.0,
                            RentStartDate = new DateTime(2024, 2, 21, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CarId = 9,
                            ClientId = 1,
                            Duration = 24.0,
                            RentStartDate = new DateTime(2024, 2, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CarId = 11,
                            ClientId = 2,
                            Duration = 36.0,
                            RentStartDate = new DateTime(2024, 2, 23, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.ModelGeneration", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.ModelGeneration", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.CarModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.RentalLog", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
